"""Created imagefile field in posts

Revision ID: 43d4b475d330
Revises: 51f5ccfba190
Create Date: 2015-03-09 21:30:02.725668

"""

# revision identifiers, used by Alembic.
revision = '43d4b475d330'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('imagefile', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'imagefile')
    ### end Alembic commands ###
